version: "3.5"

services:
  mongodb:
    container_name: mongo_dev
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - dev
  
  mongo-seed:
    build: ./docker/mongo
    depends_on:
      - mongodb
    networks:
      - dev
  
  server:
    build: 
      dockerfile: ./docker/express/Dockerfile
      context: ./
    environment:
      - DB_STRING=mongodb://host.docker.internal:27017/learn-passport
      - KEY_FOLDER=../../../keypair
      - PUB_KEY_NAME=id_rsa.pub
      - PRIV_KEY_NAME=id_rsa
      - NODE_ENV=dev
    depends_on:
      - mongodb
    networks:
      - dev
    ports:
      - 3000:3000

networks:
  dev:
    name: dev
    driver: bridge
